import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";
import Header from "@/components/layout/Header";
import Link from "next/link";
import { usePathname } from "next/navigation";
import SideBar from "@/components/layout/SideBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "min-h-screen bg-background font-sans antialiased --font-sans"
        }
      >
        <Header />
        <div className="flex">
          <SideBar />
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
